Main screen test
analogApple/pathway pull request #5
Opened 2021-05-06 12:09 UTC by analogApple

added integration test for main screen

2021-05-07 07:49 UTC, eimius requested changes
see comments

2021-05-07 07:49 UTC, eimius commented on src/screens/main/components/day-item.tsx
>  const styles = ({completed, active}: {completed: boolean; active: boolean}) => {
if, at the moment it's a function, rather than single instance (const) which is usually used with stylesheets, then please make a name that's clear and distinct, e.g. `createStyles`.

2021-05-07 07:49 UTC, eimius commented on jest-setup.js
> +});
for a bit more simple code you can just return the object
```
    jest.mock('react-native', () => ({
      Alert: {alert: jest.fn()}
}));
```

2021-05-07 07:49 UTC, eimius commented on jest-setup.js
> +  return {v4: () => 'test-uuid'};
I am not a fan of constants in tests, since the ID will be the same in all of items you are creating, which might cause problems in tests with multiple data / items. Also, not sure why you need to mock it in the first place.

2021-05-07 07:49 UTC, eimius commented on src/screens/main/components/day-item.tsx
> +          <Text testID={`${DAY_ITEM_TEST_IDS.LABEL}.${activityID}-${dayID}`}>
Can you explain how these testIDs work, since you are creating them with activityID and dayID, while in your driver you get them by a single id
```
this.getByID(`${DAY_ITEM_TEST_IDS.LABEL}.${id}`);
```
In any case, you are creating IDs dynamically, both in components and in tests, which leads us to duplication of logic when forming testIDs, and gives us an opportunity to makes mistakes while doing that. My suggestion is to put dynamic testIDs into functions, like `createTestIdForDayItemLabel` so they can be reused both in unit tests and detox tests, and in code as well.

2021-05-07 07:49 UTC, eimius commented on src/screens/main/components/day-item.tsx
> +};
testIds should be a separate file which has no imports in itself and as a result can be imported and reused in detox tests.

2021-05-07 07:49 UTC, eimius commented on server/utils/activities/find-activity-from-name.ts
> +export const findActivityFromName = (activities: Activities, name: string) => {
every exported function should have a unit test

2021-05-07 07:49 UTC, eimius commented on src/screens/main/components/activity-item.tsx
> +};
same comment about testIDs in a single separate file, otherwise you won't be able to use them in detox tests.

2021-05-07 07:49 UTC, eimius commented on src/screens/add-activity/add-activity-screen.tsx
> +  CTA: 'CTA',
same comment about testIDs in a single separate file, otherwise you won't be able to use them in detox tests.

2021-05-07 07:49 UTC, eimius commented on src/screens/add-activity/add-activity-screen.tsx
> +export const AddActivityScreen: NavigationFunctionComponent = ({
why memo was removed? can you fully trust the navigation that it does not force re-render this screen?

2021-05-07 07:49 UTC, eimius commented on src/screens/add-activity/add-activity-screen.tsx
> +  CTA: 'CTA',
what does cta means? it's an abbreviation that shouldn't be used.

2021-05-07 07:49 UTC, eimius commented on src/screens/main/components/activity-item.tsx
> +      <View marginB-s4 testID={`${ACTIVITY_ITEM_TEST_IDS.CARD}.${id}`}>
some comment about dynamic testIDs here and bellow

2021-05-07 07:49 UTC, eimius commented on src/screens/main/main-screen.driver.ts
> +    return this.getByID(`${ACTIVITY_ITEM_TEST_IDS.CARD}.${id}`);
smae comment about dynamic tests ids in components and drivers

2021-05-07 07:49 UTC, eimius commented on __tests__/app/main-screen.test.ts
> +const pressAlertActionButton = async () =>
this should be defined in the driver along with other actions such as button presses.

2021-05-07 07:49 UTC, eimius commented on __tests__/app/add-activity-screen.test.ts
> +  it('Should pop screen', () => {
not clear test name. when does the screen should pop?

2021-05-07 07:49 UTC, eimius commented on __tests__/app/add-activity-screen.test.ts
> +    expect(Navigation.pop).toBeCalledWith(componentID);
also, in this test you could also verify a side effect - that api is called with specific arguments. Since this screen is the only screen that calls it, it's the only place to test it.

2021-05-07 07:49 UTC, eimius commented on __tests__/app/main-screen.test.ts
> +    await act(async () => await screen.pressOnDayItem(day.key));
You could wrap with *act* in your driver, your test does not need to know implementation details.

2021-05-07 07:49 UTC, eimius commented on __tests__/app/main-screen.test.ts
> +  it('Activity card should render active days as active or inactive ', async () => {
This test handles 2 different flows and it would be better if you split this test into 2 tests, one that validate active day flow, other that validate inactive day flow.

The thing is that imagine if you break something with active state, then this test would fail, which would be complicated to figure out what happened since it's responsible for both active and inactive states, so you would need to debug the test. If you were two have 2 independent tests, then only a single test would break, while other test will be passing, which right from the start would give you the correct indication of what is breaking.

2021-05-13 09:22 UTC, analogApple commented on jest-setup.js
> +  return {v4: () => 'test-uuid'};
uuid creates random id, so somehow I need to access items which keys are uuid

2021-05-17 09:11 UTC, mbardauskas approved these changes
See comments, otherwise looks good

2021-05-17 09:11 UTC, mbardauskas commented on server/utils/activities/find-activity-from-name.ts
> +export const findActivityFromName = (activities: Activities, name: string) => {
That may be a practice led in the team, however, generally as a rule of thumb, any function should have a test (i.e. can be tested as part of some integration test)

2021-05-17 09:11 UTC, mbardauskas commented on src/screens/add-activity/add-activity-screen.tsx
> +  CTA: 'CTA',
I'd add that `CTA` is not acceptable abbreviation as it is too generic. I'd personally accept ADD_ACTIVITY_CTA or similar.

2021-05-17 09:11 UTC, mbardauskas commented on src/screens/main/components/day-item.tsx
> +          <Text testID={`${DAY_ITEM_TEST_IDS.LABEL}.${activityID}-${dayID}`}>
As an alternative, I react-component-driver supports filterByID instead of getByID, which returns array of all components with the same ID and thus you should be able to click on element by index. I believe detox supports that as well.

2021-05-17 09:20 UTC, mbardauskas requested changes
I see that @eimius requested changes, so I'm complying too. There are teams who approve the PRs with comments, which means that PR is good to merge once comments are sorted. Long story short, if you work with other teams and their PRs, sync on the process before-hand.

2021-05-20 11:37 UTC, merged